import { setupConventions } from "@devbox/core";
import { LocalExecutor } from "../executor.ts";
import type { Tool, ToolStatus } from "./index.ts";

// Writes ~/AGENTS.md (content generated by @devbox/core's buildAgentsMd, with
// sections gated on what was actually selected) plus, when Claude Code is
// installed, a one-line ~/.claude/CLAUDE.md that imports it as the single
// source of truth. Both are write-once — re-runs preserve user edits.
const tool: Tool = {
  id: "conventions",
  label: "Agent conventions (~/AGENTS.md)",
  default: true,
  required: true,
  async run(ctx): Promise<ToolStatus> {
    const has = (id: string) => ctx.selectedToolIds.has(id);
    return setupConventions(new LocalExecutor(), {
      repo: { owner: ctx.repo.owner, name: ctx.repo.name },
      gitMode: ctx.gitMode,
      gitWritePolicy: ctx.gitWritePolicy,
      secrets: ctx.secretsManager === "none" ? [] : [ctx.secretsManager],
      sections: {
        github: has("mcp") || has("github"),
        agentBrowser: has("agent-browser"),
        packageInstalls: has("socket") || has("ignore-scripts"),
      },
      claudeShim: has("claude"),
    });
  },
};

export default tool;
